### ISSUE TITLE
Error when reading logfile with throwable as last Event child

### ISSUE THREAD

**Issue by AleRoe** [wallymathieu/log4net-logviewer#7]
Hi there,

I was wondering if you are still maintaining this Project, as I found an issue which arrises in 
private void EventChildren(XmlReader xmlreader, Names names, LogEntry logentry)
when the last element being read is read using .ReadInnerXml.
Using ReadInnerXml causes the Reader to advance to the next node which is an ENDELEMENT. Calling xmlReader.Read() again moves the Reader past the ENDELEMENT which then throws an error because the code is expecting an ENDELEMENT. I've made a fix in my local code copy, but was hoping you could incorporate this because I prefer using a compiled package.

Thanks
Alexander

**Comment by wallymathieu** [comment]
Hi! If you want to add a pull request that would be appreciated. ;)

**Comment by AleRoe** [comment]
I feared you would say that :-)
I will give it a try.
Cheers

**Comment by wallymathieu** [comment]
Much appreciated 👍

**Comment by AleRoe** [comment]
Hi Wally,
sorry for the stupid question, but do I need to create a new branche for the Pull Request? How should I name it?
Thx
Alexander

**Comment by wallymathieu** [comment]
You can if you want. Otherwise you can just create a new pull request from your own master branch. I don't have any formal requirements for branch names. Pull requests should generally have title that describes what they want to add or fix.

**Comment by AleRoe** [comment]
Are you sure I have the appropriate rights to create a pull request? I get error 403.
(I'm working with the Github Extension right out of Visual Studio)

**Comment by wallymathieu** [comment]
Do you have your own repository on github with a fork of this code?

**Comment by wallymathieu** [comment]
Click the fork button near the top

**Comment by AleRoe** [comment]
Okay, got it working and created the pull request.
Thanks for your support!

**Comment by wallymathieu** [comment]
Merged and pushed nuget package

**Comment by wallymathieu** [comment]
Do you need an updated package with the latest log4net instead? I noticed a breaking change in a patch version of log4net.

**Comment by AleRoe** [comment]
I'm also using Common.Logging with Common.Logging.Log4Net1215. The latter requires log4net v. 2.0.5. So moving up to the latest version (2.0.8) would break dependencies. 
But you could maybe move up to 2.0.5.?
Have you thought about moving up to a newer version of the .net Framework, i.e. 4.5.2?
Cheers

**Comment by wallymathieu** [comment]
Well, log4net is published with several different frameworks in the nuget package.
If you go to:
https://www.nuget.org/packages/log4net/2.0.5
and select manual download, then unzip that file, you can see how log4net package looks. In the lib folder there are net10-full to net45-full, so if you want the package to be compatible with that package you might want do something like that.

If you have something built for .net 4.0 then you can still use it in .net 4.5.2. If you need some functionality that is present in .net 4.5.2 then that's a valid reason to upgrade. Otherwise I think it still works if you target a lower version of .net.

So, if there is some feature in .net 4.5.2 that would help for this lib, then please supply a pull request  ! :)

**Comment by AleRoe** [comment]
Fine regarding the .net Framework. I agree it only makes sense if there is some extra value in upgrading to 4.5.2.

Regarding log4net: I thought you were proposing to move up top 2.0.8. 
As 2.0.5. seems to be the current version, it might make sense to upgrade your library to 2.0.5. as well?

**Comment by wallymathieu** [comment]
Well, what would be useful?

**Comment by wallymathieu** [comment]
I don't mind if we change the lib to target 2.0.8 if that works.

**Comment by AleRoe** [comment]
Hi Oskar!
(apologies for the wrong name in previous mails)
Targeting 2.0.8. would be fine for me.
Would it be possible to give the assembly a strong name along the way?
Also, I noticed that the project descriptions on Nuget or not reflecting  the current version (see attached).
Cheers
Alexander
![nuget](https://user-images.githubusercontent.com/11810100/30103028-bac1ec6a-92f1-11e7-81a0-d6df65c06f98.png)

**Comment by wallymathieu** [comment]
Humz, doesn't look to good that the log4net version is wrong. Could be that it is one version referenced and one in the nuspec file.

**Comment by wallymathieu** [comment]
Do you need a strong name, then perhaps we should create a strong name version of the package? Upgrading to 2.0.8 for log4net sounds like a quickie 👍

**Comment by AleRoe** [comment]
That should work.
The reason I'm asking is because the assembly is used in a project which itself needs to signed. So any referenced assemblies also need to be signed/strong named.

**Comment by wallymathieu** [comment]
I can give you commit access and access to publish the nuget (so that you can fix these things), I don't have the time to focus a lot on right now.

**Comment by wallymathieu** [comment]
Or can we transfer ownership to apache (that has the ownership of log4net) ?
